/**
 * ice generate command
 *
 * Generates TypeScript types from IceType schemas.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { parseArgs } from 'node:util';
import type { IceTypeSchema, FieldDefinition } from '@icetype/core';

export async function generate(args: string[]) {
  const { values } = parseArgs({
    args,
    options: {
      schema: { type: 'string', short: 's' },
      output: { type: 'string', short: 'o' },
    },
  });

  if (!values.schema) {
    console.error('Error: --schema is required');
    console.log('Usage: ice generate --schema ./schema.ts --output ./types.ts');
    process.exit(1);
  }

  const schemaPath = values.schema as string;
  const outputPath = values.output as string || schemaPath.replace(/\.ts$/, '.generated.ts');

  console.log(`Generating types from: ${schemaPath}`);

  // For now, we'll generate a placeholder
  // In a full implementation, this would import and process the schema file
  const types = generatePlaceholderTypes();

  writeFileSync(outputPath, types);
  console.log(`Generated types: ${outputPath}`);
}

/**
 * Generate TypeScript interface from IceType schema
 */
export function generateTypeScriptInterface(schema: IceTypeSchema): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Generated from IceType schema: ${schema.name}`);
  lines.push(` * @generated`);
  lines.push(` */`);
  lines.push(``);

  // Generate the interface
  lines.push(`export interface ${schema.name} {`);

  // System fields
  lines.push(`  /** Unique document identifier */`);
  lines.push(`  $id: string;`);
  lines.push(`  /** Document type */`);
  lines.push(`  $type: '${schema.name}';`);
  lines.push(`  /** Document version */`);
  lines.push(`  $version: number;`);
  lines.push(`  /** Creation timestamp (epoch ms) */`);
  lines.push(`  $createdAt: number;`);
  lines.push(`  /** Last update timestamp (epoch ms) */`);
  lines.push(`  $updatedAt: number;`);

  // User fields
  for (const [fieldName, field] of schema.fields) {
    if (fieldName.startsWith('$')) continue;

    const tsType = fieldToTypeScript(field);
    const optional = field.isOptional ? '?' : '';
    lines.push(`  ${fieldName}${optional}: ${tsType};`);
  }

  lines.push(`}`);

  // Generate input type (without system fields)
  lines.push(``);
  lines.push(`/** Input type for creating ${schema.name} */`);
  lines.push(`export interface ${schema.name}Input {`);

  for (const [fieldName, field] of schema.fields) {
    if (fieldName.startsWith('$')) continue;

    const tsType = fieldToTypeScript(field);
    const optional = field.isOptional || field.defaultValue !== undefined ? '?' : '';
    lines.push(`  ${fieldName}${optional}: ${tsType};`);
  }

  lines.push(`}`);

  return lines.join('\n');
}

/**
 * Convert IceType field to TypeScript type
 */
function fieldToTypeScript(field: FieldDefinition): string {
  if (field.relation) {
    // Relations become string IDs or arrays of string IDs
    if (field.isArray) {
      return 'string[]';
    }
    return 'string';
  }

  let baseType: string;

  switch (field.type.toLowerCase()) {
    case 'string':
    case 'text':
    case 'uuid':
      baseType = 'string';
      break;
    case 'int':
    case 'long':
    case 'bigint':
    case 'float':
    case 'double':
    case 'decimal':
      baseType = 'number';
      break;
    case 'bool':
    case 'boolean':
      baseType = 'boolean';
      break;
    case 'timestamp':
    case 'timestamptz':
    case 'date':
    case 'time':
      baseType = 'number'; // Epoch ms
      break;
    case 'json':
      baseType = 'unknown';
      break;
    case 'binary':
      baseType = 'Uint8Array';
      break;
    default:
      baseType = 'unknown';
  }

  if (field.isArray) {
    return `${baseType}[]`;
  }

  return baseType;
}

function generatePlaceholderTypes(): string {
  return `/**
 * IceType Generated Types
 *
 * This file was generated by 'ice generate'.
 * Do not edit manually - changes will be overwritten.
 *
 * @generated
 */

// To generate actual types, the CLI needs to import and evaluate your schema file.
// This is a placeholder showing the expected output format.

export interface User {
  $id: string;
  $type: 'User';
  $version: number;
  $createdAt: number;
  $updatedAt: number;
  id: string;
  email: string;
  name: string;
  bio?: string;
  tenantId: string;
  role: string;
  status: string;
  posts: string[];
  organization?: string;
}

export interface UserInput {
  id?: string;
  email: string;
  name: string;
  bio?: string;
  tenantId: string;
  role?: string;
  status?: string;
  posts?: string[];
  organization?: string;
}
`;
}
