// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"adapters.mdx": () => import("../../../docs/adapters.mdx?collection=docs"), "cli.mdx": () => import("../../../docs/cli.mdx?collection=docs"), "document-formats.mdx": () => import("../../../docs/document-formats.mdx?collection=docs"), "errors.mdx": () => import("../../../docs/errors.mdx?collection=docs"), "examples.mdx": () => import("../../../docs/examples.mdx?collection=docs"), "getting-started.mdx": () => import("../../../docs/getting-started.mdx?collection=docs"), "index.mdx": () => import("../../../docs/index.mdx?collection=docs"), "schema-language.mdx": () => import("../../../docs/schema-language.mdx?collection=docs"), "stability.mdx": () => import("../../../docs/stability.mdx?collection=docs"), "vs-drizzle.mdx": () => import("../../../docs/vs-drizzle.mdx?collection=docs"), "vs-prisma.mdx": () => import("../../../docs/vs-prisma.mdx?collection=docs"), "why-icetype.mdx": () => import("../../../docs/why-icetype.mdx?collection=docs"), "api/adapters.mdx": () => import("../../../docs/api/adapters.mdx?collection=docs"), "api/clickhouse.mdx": () => import("../../../docs/api/clickhouse.mdx?collection=docs"), "api/core.mdx": () => import("../../../docs/api/core.mdx?collection=docs"), "api/drizzle.mdx": () => import("../../../docs/api/drizzle.mdx?collection=docs"), "api/duckdb.mdx": () => import("../../../docs/api/duckdb.mdx?collection=docs"), "api/iceberg.mdx": () => import("../../../docs/api/iceberg.mdx?collection=docs"), "api/mysql.mdx": () => import("../../../docs/api/mysql.mdx?collection=docs"), "api/postgres.mdx": () => import("../../../docs/api/postgres.mdx?collection=docs"), "api/prisma.mdx": () => import("../../../docs/api/prisma.mdx?collection=docs"), "api/sqlite.mdx": () => import("../../../docs/api/sqlite.mdx?collection=docs"), "walkthroughs/analytics-pipeline.mdx": () => import("../../../docs/walkthroughs/analytics-pipeline.mdx?collection=docs"), "walkthroughs/e-commerce.mdx": () => import("../../../docs/walkthroughs/e-commerce.mdx?collection=docs"), "walkthroughs/production-deployment.mdx": () => import("../../../docs/walkthroughs/production-deployment.mdx?collection=docs"), "tutorials/drizzle-integration.mdx": () => import("../../../docs/tutorials/drizzle-integration.mdx?collection=docs"), "tutorials/iceberg-analytics.mdx": () => import("../../../docs/tutorials/iceberg-analytics.mdx?collection=docs"), "tutorials/migration-workflow.mdx": () => import("../../../docs/tutorials/migration-workflow.mdx?collection=docs"), "tutorials/video-scripts/getting-started.md": () => import("../../../docs/tutorials/video-scripts/getting-started.md?collection=docs"), }),
};
export default browserCollections;